server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: app_python
  static_configs:
  - targets:
      - localhost
    labels:
      job: python_logs
      __path__: /var/log/app_python/*log

- job_name: app_java
  static_configs:
  - targets:
      - localhost
    labels:
      job: java_logs
      __path__: /var/log/app_java/*log

- job_name: docker_containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<container_name>(?:[^|]*[^|]))
      source: tag
  - labels:
      # tag:
      stream:
      container_name:
  - output:
      source: output
