apiVersion: v1
kind: Service
metadata:
  name: {{ include "python_app-helm.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/port: '5000'

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "library-chart.labels" . | indent 4 }}
