apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time
  template:
    metadata:
      labels:
        app: moscow-time
    spec:
      containers:
      - name: moscow-time
        image: fk12344321/moscow-time:mac
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
